const FONT_PRIMARY = "Readex Pro, sans-serif";

const headers = {
  ["headerxxl-bold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 700,
    fontSize: "72px",
    color: "#333333",
    letterSpacing: "-1.5px",
    lineHeight: "80px",
  },
  ["headerxxl-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "72px",
    color: "#333333",
    letterSpacing: "-1.5px",
    lineHeight: "80px",
  },
  ["headerxl-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "40px",
    color: "#333333",
    letterSpacing: "-0.5px",
    lineHeight: "48px",
  },
  ["headerlg-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontStyle: "normal",
    fontSize: "32px",
    color: "#333333",
    letterSpacing: "-0.25px",
    lineHeight: "40px",
  },
  ["headermd-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontStyle: "normal",
    fontSize: "25px",
    color: "#333333",
    letterSpacing: "-0.25px",
    lineHeight: "34px",
  },
  ["headersm-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "20px",
    color: "#333333",
    letterSpacing: "-0.15px",
    lineHeight: "28px",
  },
  ["headerxs-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "16px",
    color: "#333333",
    lineHeight: "22px",
  },
};

const body = {
  ["bodyxl-bold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 700,
    fontSize: "18px",
    color: "#333333",
    lineHeight: "26px",
  },
  ["bodyxl-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "18px",
    color: "#333333",
    lineHeight: "26px",
  },
  ["bodyxl-medium"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 500,
    fontSize: "18px",
    color: "#333333",
    lineHeight: "26px",
  },
  ["bodylg-bold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 700,
    fontSize: "16px",
    color: "#333333",
    lineHeight: "23px",
  },
  ["bodylg-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "16px",
    color: "#333333",
    lineHeight: "23px",
  },
  ["bodylg-medium"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 500,
    fontSize: "16px",
    color: "#333333",
    lineHeight: "23px",
  },
  ["bodymd-bold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 700,
    fontSize: "15px",
    color: "#333333",
    lineHeight: "22px",
  },
  ["bodymd-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "15px",
    color: "#333333",
    lineHeight: "22px",
  },
  ["bodymd-medium"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 500,
    fontSize: "15px",
    color: "#333333",
    lineHeight: "22px",
  },
  ["bodysm-bold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 700,
    fontSize: "13px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodysm-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "13px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodysm-medium"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 500,
    fontSize: "13px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodyxs-bold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 700,
    fontSize: "12px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodyxs-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "12px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodyxs-medium"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 500,
    fontSize: "12px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodyxxs-bold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 700,
    fontSize: "11px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodyxxs-semibold"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "11px",
    color: "#333333",
    lineHeight: "20px",
  },
  ["bodyxxs-medium"]: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 500,
    fontSize: "11px",
    color: "#333333",
    lineHeight: "20px",
  },
};

// This object is deprecated and will be removed in the future,
// please use the new `headers` and `body` objects above and add new typographies to their respective objects
const deprecatedTypography = {
  fontFamily: FONT_PRIMARY,
  fontWeightRegular: 400,
  fontWeightMedium: 600,
  fontWeightBold: 700,
  fontSize: 15,
  h1: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "35px",
    lineHeight: "38px",
    letterSpacing: "-.05px",
  },
  h2: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "25px",
    lineHeight: "31px",
    letterSpacing: "-.25px",
  },
  h3: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "15px",
    lineHeight: "25px",
    letterSpacing: "-.15px",
  },
  h4: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "22px",
  },
  section: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "20px",
    lineHeight: "30px",
  },
  sectionSmall: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "30px",
  },
  body1: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 400,
    fontSize: "15px",
    lineHeight: "22px",
  },
  body2: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
  },
  body3: {
    fontFamily: FONT_PRIMARY,
    fontWeight: 400,
    fontSize: "13px",
    lineHeight: "20px",
  },
  link: {
    fontFamily: FONT_PRIMARY,
    fontWeight: "550",
    color: "#017971",
    cursor: "pointer",
    textDecoration: "underline",
  },
};

const typography = {
  ...deprecatedTypography,
  ...headers,
  ...body,
};

export default typography;
